### ISSUE TITLE
Change Terminology

### ISSUE THREAD

**Issue by Kalaschnik** [rcdexta/react-trello#126]
I noticed you refer to lane when describing an actual column in the data. Lanes (or swim lanes) are a separate horizontal structure in most Kanban applications (such as Jira). Did you have thought about changing the namings?

Best,
Kalaschnik

**Comment by G-Rath** [comment]
Interesting point. Trello calls them 'lists'.

I think that `lanes` still makes sense, as the best method of doing swimlanes with this library is by just using multiple boards.

Besides, renaming would require a large change across the entire project, for very little gain. 

It might be worth it if swimlane support was introduced, since it'd likely lead to confusion, but for now I don't think (& hope it's not) it's confusing anyone 😃
