### ISSUE TITLE
Switch to componentDidMount()

### ISSUE THREAD

**Issue by Kalaschnik** [rcdexta/react-trello#134]
I noticed the board is using:

```
async componentWillMount() {
    const response = await this.getBoard()
    this.setState({boardData: response})
}
```
It is, however, deprecated:

> **Note**
> _This lifecycle was previously named componentWillMount. That name will continue to work until version 17. Use the rename-unsafe-lifecycles codemod to automatically update your components._

More here:
https://reactjs.org/docs/react-component.html#unsafe_componentwillmount

**Comment by G-Rath** [comment]
@Kalaschnik thanks for pointing that out - definitely something to fix. 

What file did that code come from? I can't find it in the sources. 

I did find this:

https://github.com/rcdexta/react-trello/blob/bb6a099016acb1cac12d028c4d26ccb10ecf4120/src/components/BoardContainer.js#L24-L30 

which should be changed. 

@rcdexta since you know the package better than I do, do you want to take this one?

You should just be able to move that into the `constructor`.
