### ISSUE TITLE
I pushed card using eventBus method.  while pushing the card again It's getting overwritten with the previous card. ? 

### ISSUE THREAD

**Issue by thisisrajkumar** [rcdexta/react-trello#151]

**Comment by G-Rath** [comment]
@thisisrajkumar please use the appropriate issue template when reporting issues.

Please also provide more information on the problem that you've having, ideally including a minimal code example, and details on what you're trying to accomplish, what you've already tried, and why you think what's happening is a bug or a feature covered by this package.

**Comment by thisisrajkumar** [comment]
// Declaring eventbus state value
    this.state = {
      eventBus: undefined
    }
// set the eventbus method using state value

  setEventBus = eventBus => {
    this.setState({ eventBus })
  }

    if (this.props.learningjourney.pushtheme != null) {
//pushtheme is one card object. like `{type: 'ADD_CARD', laneId: 'COMPLETED', card: {id: "M1", title: "Buy Milk", label: "15 mins", description: "Also set reminder"}}`
   eventBus.publish(pushtheme);
}

<div className="App-intro">
                <Board
                  editable={true}
                  // onCardAdd={this.handleCardAdd}
                  onCardClick={this.clickCard}
                  data={this.props.learningjourney.data}
                  draggable
                  hideCardDeleteIcon
                  onDataChange={this.shouldReceiveNewData}
                  eventBusHandle={this.setEventBus}
                  addCardLink={<button disabled={this.state.btndisable}>Add Card</button>}
                  newCardTemplate={<NewCard propsval={this.props} state={this.state} />} />
              </div>

I am using API call for insert card data. After API call success I trigger this   **eventBus.publish(pushtheme);**  method.  After that I try to push the another card again It's getting write with the previous card.  My existing card is gone . I can't push card in dynamically.

**Comment by G-Rath** [comment]
I can't really provide much help on this since I don't know anything about your application, and this is very much an implementation problem on your side, vs a bug on our side.

You should provide a small repository or application example containing a *complete working application* to work off, as the code you've provided doesn't have any context; those code snippets could be completely separate from each other.

A key thing to keep in mind is that if you cause a re-renderer of the `Board` component, that'll cause it to 'reset' to whatever the value of `data` is; this means that if you add a card using the `eventBus`, you should make sure that that `learningjourney.data` gets that card at somepoint too.

My advice is to try and stay away from using the `eventBus` - it's mainly for very advance use-cases, as in using it you have to ensure you keep your `data` in sync with whatever changes you push using `eventBus`.

Instead, just apply whatever changes you want to make to `learningjourney.data`.

If things are still unclear to you, I can provide you with a very basic minimal component showing off how you should implement the `Board`, but can't make any promises due to my workload.
