### ISSUE TITLE
IE11 Template string issue

### ISSUE THREAD

**Issue by RaulTsc** [rcdexta/react-trello#152]
**Describe the bug**
IE11 throws an 'Invalid character' error because template strings do not work - https://caniuse.com/#search=template%20strings

**To Reproduce**
Bundle react-trello and run it in IE11

**Expected behavior**
It should work

**Screenshots**
https://imgur.com/a/D1AspSW (the error is thrown at injectGlobal`). I don't have a screenshot of the error but it's just an uncaught exception.

**Desktop (please complete the following information):**
Windows 7 / IE11

You can try using the transform template literals babel plugin to fix it (I am not sure if it's you or styled-components that should implement the fix)
https://babeljs.io/docs/en/babel-plugin-transform-es2015-template-literals

Thanks

**Comment by rcdexta** [comment]
This should be fixed in the latest release. Tested on IE 11 and did not see any console errors.

<img width="358" alt="screen shot 2018-12-29 at 7 00 32 pm" src="https://user-images.githubusercontent.com/900028/50544000-912d9c80-0b9c-11e9-9f78-7baedec80a02.png">
<img width="1360" alt="screen shot 2018-12-29 at 7 00 24 pm" src="https://user-images.githubusercontent.com/900028/50544001-912d9c80-0b9c-11e9-8b38-2009278b5e88.png">

Thanks for the detailed report on the issue!
