### ISSUE TITLE
Remove style hardcoding

### ISSUE THREAD

**Issue by dapi** [rcdexta/react-trello#258]
```
src/components/BoardContainer.js:              <LaneSection style={{width: 200}}>
src/components/NewCard.js:      <div style={{background: '#E3E3E3'}}>
```

**Comment by asonawan** [comment]
Hi @dapi,
I have just seen your previous issue where you have shown interest in maintaining the project, 
recently I have added this package to my project and what I have realised that the customisation of lanes and cards is too complicated, it could have been simplified just by passing a class and style from addition user configuration rather than just relying on the CSS object.

For eg., if I want to have multiple predefined themes for the lanes and cards then I cannot have it in the CSS and I will always have to pass CSS config to the lane and task object

**Comment by dapi** [comment]
@asonawan thank you for option. After 2 weeks of using this project I have similar one )

Also i've changed the way to pass custom NewLane and other components:

https://github.com/BrandyMint/react-trello/pull/1/files#diff-ec6ba09dae0e5a38d6c4be664c98b7bdR12
https://github.com/BrandyMint/react-trello/pull/1/files#diff-ec6ba09dae0e5a38d6c4be664c98b7bdR185
https://github.com/BrandyMint/react-trello/pull/1/files#diff-ec6ba09dae0e5a38d6c4be664c98b7bdR234

Planning to use this approach to pass other components (like NewCard and Card)

**Comment by dapi** [comment]
Here is a reason to stay `react-trello` as component which has bounded responsibilities. As I see now it has too much responsibilities.

Probably minimal list is:

* Show lanes and cards
* Drag lanes and carads
* Gives dependency injection mechanism to customise all used components: `Lane` (and its header, body and footer), `Card`, `NewLane`

**Comment by asonawan** [comment]
@dapi exactly my thought, it should be a simple component which just does the things which you have mentioned and let the user give a simpler way to style things.

**Comment by asonawan** [comment]
@dapi exactly my thought, it should be a simple component which just does the things which you have mentioned and let the user give a simpler way to style things.
By the way, when are you planning to release this?

**Comment by dapi** [comment]
I will know it in a week
