### ISSUE TITLE
Add lane error

### ISSUE THREAD

**Issue by LucasBadico** [rcdexta/react-trello#382]
**Describe the bug**
We are trying to integrate the `add lane` button when we get back a console error and an error shows up on the console.

**To Reproduce**
1. Go to https://rcdexta.com/react-trello/?selectedKind=Editable%20Board&selectedStory=Add%20New%20Lane&full=0&addons=0&stories=1&panelRight=0
2. Click on `add new lane` button
3. Button goes away. If is on the application itself you get an error on console.

**Expected behavior**
Open a new lane form.

**Screenshots**
<img width="587" alt="Captura de Tela 2020-06-07 às 16 33 05" src="https://user-images.githubusercontent.com/16516889/83978263-97b95b00-a8dc-11ea-9492-9bc8406b50c2.png">

**Desktop (please complete the following information):**
 - OS: Linux and Mac OS.
 - Browser: Chrome and firefox

**Comment by LucasBadico** [comment]
We where able to get rid of this error going back to v2.2.2.

**Comment by wate123** [comment]
add lane is not working in 2.2.2 too.

**Comment by rcdexta** [comment]
check 2.2.8 release

**Comment by internationalhouseofdonald** [comment]
This error is still present in v2.2.8. Any updates? 👉🏼👈🏼 😶

**Comment by internationalhouseofdonald** [comment]
For anyone wondering, you have to update to react-trello@2.2.8 _and_ restart your dev server in order for these changes to take place.

I believe this might be because there is no declaration file for the package.
![image](https://user-images.githubusercontent.com/20768148/88852473-efc15f00-d1b3-11ea-9544-c63506e906e4.png)
