### ISSUE TITLE
Option to edit a card?

### ISSUE THREAD

**Issue by SoorajChandran** [rcdexta/react-trello#99]
Is there an option to edit a card? Couldn't find in the docs. If its not already there, would like to contribute to the repo.

On click a form with the existing fields would pop-up, with the values populated and a  save/add button. 

How I tried implementing this is, on clicking a hypothetical edit button, I would delete the card and show the add new card form, with the data populated. Not sure if the proposal is stupid. or if there is an easier implementation.

**Comment by rcdexta** [comment]
I was contemplating about inline edit for existing cards. But, it can get complicated soon since the library allows the following customisations:

- allow adding tags to the card
- allow passing a custom template for the card

So, editing the card will be intentionally outside the scope of this library. But, just like the original trello opens up a modal to edit all card attributes on clicking the card, you can use the `onCardClick` handler to get the card details and implement your own card editing functionality as needed.

@SoorajChandran if you do have other ideas for offering card edit functionality a part of the library, you are welcome to contribute and submit a PR. Would be happy to review and merge it.

Closing the issue for now...
